#!/usr/bin/env python3
"""Individual Exercise 3: PCA whitening and reciprocal query expansion."""

from __future__ import annotations

import argparse
import gzip
import pickle
from pathlib import Path
from typing import Iterable

import numpy as np
from sklearn.decomposition import PCA


def parse_int_list(value: str) -> list[int]:
    """Parse a comma-separated list of positive integers."""
    result = [int(item.strip()) for item in value.split(",") if item.strip()]
    if not result or any(item <= 0 for item in result):
        raise argparse.ArgumentTypeError("Expected comma-separated positive integers.")
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate PCA whitening and reciprocal query expansion on VLAD encodings."
    )
    parser.add_argument("--enc-train", default="enc_train.pkl.gz", help="Training VLAD cache")
    parser.add_argument("--enc-test", default="enc_test.pkl.gz", help="Test VLAD cache")
    parser.add_argument(
        "--labels-test", default="icdar17_labels_test.txt", help="Test label file"
    )
    parser.add_argument(
        "--pca-dims",
        type=parse_int_list,
        default=[1024],
        help="PCA dimensions, e.g. 128,256,512,1024",
    )
    parser.add_argument(
        "--rqe-k",
        type=parse_int_list,
        default=[3],
        help="Neighbourhood sizes for R-QE on the original VLAD features",
    )
    parser.add_argument(
        "--combined-k",
        type=parse_int_list,
        default=[4],
        help="Neighbourhood sizes for R-QE after the best PCA setting",
    )
    parser.add_argument(
        "--best-pca-dim",
        type=int,
        default=1024,
        help="PCA dimension used for the combined experiment",
    )
    parser.add_argument(
        "--output", default="individual_exercise3_results.txt", help="Result text file"
    )
    return parser.parse_args()


def load_pickle_gz(path: str | Path) -> np.ndarray:
    """Load a trusted gzip-compressed pickle generated by the group code."""
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Encoding file not found: {path}")
    with gzip.open(path, "rb") as file_handle:
        array = pickle.load(file_handle)
    array = np.asarray(array, dtype=np.float32)
    if array.ndim != 2 or not np.isfinite(array).all():
        raise ValueError(f"Invalid encoding matrix in {path}: shape={array.shape}")
    return array


def load_labels(path: str | Path) -> np.ndarray:
    """Load the writer ID from the second column of the official label file."""
    labels: list[str] = []
    with Path(path).open("r", encoding="utf-8") as file_handle:
        for line_number, line in enumerate(file_handle, start=1):
            fields = line.split()
            if len(fields) < 2:
                raise ValueError(f"Malformed label line {line_number}: {line!r}")
            labels.append(fields[1])
    return np.asarray(labels)


def l2_normalize(features: np.ndarray) -> np.ndarray:
    """L2-normalize every row."""
    norms = np.linalg.norm(features, axis=1, keepdims=True)
    return (features / np.maximum(norms, 1e-12)).astype(np.float32, copy=False)


def evaluate_similarity(similarity: np.ndarray, labels: np.ndarray) -> tuple[float, float]:
    """Return Top-1 accuracy and mAP using the group exercise protocol."""
    if similarity.shape != (len(labels), len(labels)):
        raise ValueError(
            f"Expected a square {len(labels)}x{len(labels)} matrix, got {similarity.shape}."
        )

    scores = np.asarray(similarity, dtype=np.float32).copy()
    np.fill_diagonal(scores, -np.inf)  # exclude the query image itself
    ranking = np.argsort(-scores, axis=1)[:, : len(labels) - 1]
    relevant = labels[ranking] == labels[:, None]

    top1 = float(np.mean(relevant[:, 0]))
    cumulative_relevant = np.cumsum(relevant, axis=1)
    ranks = np.arange(1, len(labels), dtype=np.float32)
    precision_at_rank = cumulative_relevant / ranks[None, :]
    relevant_per_query = np.sum(relevant, axis=1)
    average_precision = np.sum(precision_at_rank * relevant, axis=1) / relevant_per_query
    mean_average_precision = float(np.mean(average_precision))
    return top1, mean_average_precision


def evaluate_features(
    query_features: np.ndarray,
    labels: np.ndarray,
    gallery_features: np.ndarray | None = None,
) -> tuple[float, float]:
    """Evaluate cosine similarity between query and gallery representations."""
    gallery = query_features if gallery_features is None else gallery_features
    similarity = np.asarray(query_features @ gallery.T, dtype=np.float32)
    return evaluate_similarity(similarity, labels)


def fit_pca_whitening(
    train_features: np.ndarray,
    test_features: np.ndarray,
    n_components: int,
) -> tuple[np.ndarray, float]:
    """Fit PCA only on training VLAD vectors, whiten test vectors, then L2-normalize."""
    maximum = min(train_features.shape)
    if n_components > maximum:
        raise ValueError(
            f"PCA dimension {n_components} is too large; maximum is {maximum}."
        )

    pca = PCA(
        n_components=n_components,
        whiten=True,
        svd_solver="randomized",
        iterated_power=3,
        random_state=42,
    )
    pca.fit(train_features)
    transformed_test = pca.transform(test_features).astype(np.float32)
    transformed_test = l2_normalize(transformed_test)
    explained_variance = float(np.sum(pca.explained_variance_ratio_))
    return transformed_test, explained_variance


def reciprocal_query_expansion(
    features: np.ndarray,
    k: int,
) -> tuple[np.ndarray, float]:
    """Expand each query using reciprocal top-k neighbours."""
    if k >= len(features):
        raise ValueError("k must be smaller than the number of test samples.")

    similarity = np.asarray(features @ features.T, dtype=np.float32)
    np.fill_diagonal(similarity, -np.inf)
    ranking = np.argsort(-similarity, axis=1)

    expanded = features.copy()
    reciprocal_counts = np.zeros(len(features), dtype=np.int32)

    for query_index in range(len(features)):
        candidates = ranking[query_index, :k]
        reciprocal = [
            int(candidate)
            for candidate in candidates
            if query_index in ranking[candidate, :k]
        ]
        reciprocal_counts[query_index] = len(reciprocal)
        if reciprocal:
            expanded[query_index] = (
                features[query_index] + np.sum(features[reciprocal], axis=0)
            )

    expanded = l2_normalize(expanded)
    return expanded, float(np.mean(reciprocal_counts))


def format_result(name: str, top1: float, mean_ap: float, note: str = "") -> str:
    suffix = f" | {note}" if note else ""
    return (
        f"{name:<32} Top-1: {top1:.6f} ({100.0 * top1:6.2f}%)"
        f" | mAP: {mean_ap:.6f}{suffix}"
    )


def write_lines(path: str | Path, lines: Iterable[str]) -> None:
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()

    train_features = load_pickle_gz(args.enc_train)
    test_features = load_pickle_gz(args.enc_test)
    labels = load_labels(args.labels_test)

    if len(train_features) != 1182:
        print(f"Warning: expected 1182 training encodings, found {len(train_features)}.")
    if len(test_features) != len(labels):
        raise ValueError(
            f"Test encodings ({len(test_features)}) and labels ({len(labels)}) do not match."
        )

    train_features = l2_normalize(train_features)
    test_features = l2_normalize(test_features)

    result_lines = [
        "Individual Exercise 3 - Writer Retrieval Experiments",
        f"Train encodings: {train_features.shape}",
        f"Test encodings:  {test_features.shape}",
        "",
    ]

    baseline = evaluate_features(test_features, labels)
    result_lines.append(format_result("Baseline VLAD", *baseline))

    result_lines.append("")
    result_lines.append("Experiment 1: PCA whitening")
    pca_cache: dict[int, np.ndarray] = {}
    for dimension in args.pca_dims:
        transformed, explained_variance = fit_pca_whitening(
            train_features, test_features, dimension
        )
        pca_cache[dimension] = transformed
        result = evaluate_features(transformed, labels)
        result_lines.append(
            format_result(
                f"PCA-whitened VLAD ({dimension}D)",
                *result,
                note=f"explained variance={explained_variance:.4f}",
            )
        )

    result_lines.append("")
    result_lines.append("Experiment 2: Reciprocal query expansion on original VLAD")
    for k in args.rqe_k:
        expanded, average_reciprocal_count = reciprocal_query_expansion(test_features, k)
        result = evaluate_features(expanded, labels, gallery_features=test_features)
        result_lines.append(
            format_result(
                f"R-QE on VLAD (k={k})",
                *result,
                note=f"avg. reciprocal neighbours={average_reciprocal_count:.3f}",
            )
        )

    result_lines.append("")
    result_lines.append("Experiment 3: PCA whitening followed by reciprocal query expansion")
    if args.best_pca_dim in pca_cache:
        pca_features = pca_cache[args.best_pca_dim]
    else:
        pca_features, _ = fit_pca_whitening(
            train_features, test_features, args.best_pca_dim
        )

    for k in args.combined_k:
        expanded, average_reciprocal_count = reciprocal_query_expansion(pca_features, k)
        result = evaluate_features(expanded, labels, gallery_features=pca_features)
        result_lines.append(
            format_result(
                f"PCA {args.best_pca_dim}D + R-QE (k={k})",
                *result,
                note=f"avg. reciprocal neighbours={average_reciprocal_count:.3f}",
            )
        )

    output_text = "\n".join(result_lines)
    print(output_text)
    write_lines(args.output, result_lines)
    print(f"\nSaved results to: {Path(args.output).resolve()}")


if __name__ == "__main__":
    main()
